### ISSUE TITLE
Implement CI using any cloud provider 

### ISSUE THREAD

**Issue by moshloop** [mpumelelongema/htmlreader#1]

**Comment by mpumelelongema** [comment]
I have configured my project to use CircleCI, this is the URL https://circleci.com/gh/mpumelelongema/htmlreader

It builds fine but fails when it runs 1 test, it seems the test case doesn't connect to and retrieve the details from the Technology Stack web page as the response comes back empty.

I will have a look at this later but I based on the requirements of the issue I have configure a CI for the project, can I close this task so long and we open a separate task for the failing test on CircleCI..??

**Comment by moshloop** [comment]
Yes, you can open a new task and close this one.
For the next task, propose the changes to fix the failing test case using a pull request
